- name: Install packages
  package:
    name:
      - xorg
      - xorg-xinit
      - xorg-xmodmap
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - fcitx-im
      - fcitx-mozc
      - fcitx-configtool
      - lm_sensors
      - dmenu
      - alsa-utils
      - pulseaudio
      - pavucontrol
      - bluez
      - bluez-utils
      - blueman
      - gnome
      - dconf-editor
      - xf86-input-libinput
      - xorg-xinput
    state: present
  become: yes

- name: aur install
  kewlfft.aur.aur:
    use: yay
    name:
      - ttf-cica
      - google-chrome
      - visual-studio-code-bin
      - chrome-gnome-shell
      - libinput-gestures
  become: yes
  become_user: aur_builder

- name: Make sure environment variables are defined
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
  become: yes

- name: Make sure directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/X11

- name: Ensure dotfiles (files) are symlinked
  file:
    src: "{{ ansible_env.PWD }}/roles/desktop_environment/files/{{ item.filename }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { filename: X11/xinitrc, dest: ~/.config/X11/xinitrc }
    - { filename: misc/xprofile, dest: ~/.xprofile }
    - { filename: misc/Xmodmap, dest: ~/.Xmodmap }
    - { filename: misc/libinput-gestures.conf, dest: ~/.config/libinput-gestures.conf }

- name: "ALSA configuration"
  lineinfile:
      path: /etc/modprobe.d/alsa_base.conf
      line: 'options snd_hda_intel model=alc256-asus-mic power_save=0 power_save_controller=N'
      create: yes
  become: yes

# Bluetoothのためユーザーをlpグループに追加。
# https://wiki.archlinux.jp/index.php/Bluetooth
- name: adding existing user '{{ USER_NAME }}' to group lp, input
  user:
    name: '{{ USER_NAME }}'
    groups:
      - lp
      - input
    append: yes
  become: yes

- name: Make sure the GDM service is running
  systemd:
    name: gdm.service
    state: started
    enabled: yes
  become: yes


- name: Make sure the NetworkManager service is running
  systemd:
    name: NetworkManager.service
    state: started
    enabled: yes
  become: yes
