- name: Set up localhost
  hosts: local
  pre_tasks:
    - name: Show variables
      debug:
        msg:
          OS: "{{ ansible_os_family }}"
          Host name: "{{ ansible_hostname }}"
          User name: "{{ ansible_env.USER }}"
    - name: Assert that user is {{ USER_NAME }}
      assert:
        that:
          - ansible_env.USER == '{{ USER_NAME }}'
        fail_msg: "user must be {{ USER_NAME }}"
        success_msg: "user is {{ USER_NAME }}"
    # - name: Run the equivalent of "pacman -Syu" as a separate step
    #   pacman:
    #     update_cache: yes
    #     upgrade: yes
    #   become: yes
  roles:
    - role: role20240916
    - role: cimon-io.asdf
      asdf_user: "{{ USER_NAME }}"
      asdf_group: "{{ USER_NAME }}"
      asdf_plugins:
        - name: python
          versions:
            - 3.13.0
          global: system
        - name: awscli
          versions: [2.7.35]
          global: 2.7.35
