- name: Set up user
  hosts: local
  vars_files:
   - group_vars/local.yml
  tasks:
    - name: debug var
      debug:
        msg:
          OS: "{{ ansible_os_family }}"
          Host name: "{{ ansible_hostname }}"
          User name: "{{ ansible_env.USER }}"

    - name: Assert that user is root
      assert:
        that:
          - ansible_env.USER == 'root'
        fail_msg: "user must be root"
        success_msg: "user is root"

    - name: Ensure a locale exists
      community.general.locale_gen: name={{ item }} state=present
      with_items:
        - en_US.UTF-8
        - ja_JP.UTF-8

    - name: Ensure group "wheel" exists
      group:
        name: wheel

    - name: Make sure users in the wheel group can sudo without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^# %wheel ALL=(ALL) NOPASSWD: ALL'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/sbin/visudo -c -f %s'

    - name: Ensure user '{{ USER_NAME }}' exists
      user:
        name: "{{ USER_NAME }}"
        shell: /bin/bash
        create_home: yes
        generate_ssh_key: yes
        comment: "{{ USER_NAME }}"
        groups:
          - wheel

    - name: Create user to aur_builder
      user:
        name: aur_builder
        group: wheel
      become: yes

    - name: Configure user aur_builder
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'
      become: yes

