- name: 公式のパッケージをインストールする
  package:
    name:
      - bluez
      - bluez-utils
      - usbutils
    state: present
  become: yes

- name: システムレベルの設定ファイルのリンクを作成する
  file:
    src: "{{ ansible_env.PWD }}/roles/{{ ansible_role_name }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    # サスペンドから復帰する
    # Bluetooth - ArchWiki サスペンドからの復帰
    # https://wiki.archlinux.jp/index.php/Bluetooth#.E3.82.B5.E3.82.B9.E3.83.9A.E3.83.B3.E3.83.89.E3.81.8B.E3.82.89.E3.81.AE.E5.BE.A9.E5.B8.B0
    - src: system/91-keyboard-mouse-wakeup.rules
      dest: /etc/udev/rules.d/91-keyboard-mouse-wakeup.rules
  become: yes

# Bluetooth - ArchWikiBluetooth - ArchWiki 起動後に自動で有効にする
# https://wiki.archlinux.jp/index.php/Bluetooth#.E8.B5.B7.E5.8B.95.E5.BE.8C.E3.81.AB.E8.87.AA.E5.8B.95.E3.81.A7.E6.9C.89.E5.8A.B9.E3.81.AB.E3.81.99.E3.82.8B
- name: 起動/サスペンド解除後に後に自動でBluetoothを有効にする
  lineinfile:
    path: /etc/bluetooth/main.conf
    state: present
    regexp: '^#AutoEnable=false'
    line: 'AutoEnable=true'
  become: yes
