- name: Install packages
  package:
    name:
      - less
      - fzf
      - fcitx5
      - fcitx5-configtool
      - fish
      - neofetch
      - starship
      - neovim
      - unzip
      - wl-clipboard
    state: present
  become: yes

- name: aur install
  kewlfft.aur.aur:
    use: yay
    name:
      - ttf-hackgen  # プログラミングフォント 白源 (はくげん／HackGen)
      - fcitx5-mozc-ut
      - ghq
      - visual-studio-code-bin
      - asdf-vm
  become: yes
  become_user: aur_builder

- name: Make sure directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/Code/User
    - ~/.config/nvim
    - ~/.config/git
    - ~/.local/share/nvim/site/autoload
    - ~/.config/neofetch
    - ~/.config/fish

- name: Ensure dotfiles (files) are symlinked
  file:
    src: "{{ ansible_env.PWD }}/roles/{{ ansible_role_name }}/files/{{ item }}"
    dest: ~/{{ item }}
    state: link
  with_items:
    - .config/Code/User/keybindings.json
    - .config/Code/User/settings.json
    - .config/git/ignore
    - .config/nvim/init.vim
    - .config/chrome-flags.conf
    - .config/code-flags.conf
    - .config/neofetch/config.conf
    - .config/fish/config.fish
    - .config/fish/fzf_key_bindings.fish

- name: Ensure dotfiles (template) are placed
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: gitconfig.j2, dest: ~/.config/git/config }

- name: Download Vim-Plug script
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Install Vim-Plug plugins
  shell: nvim --headless +PlugInstall +qall
  args:
    creates: ~/.config/nvim/plugged
    executable: /bin/bash
