- name: wineインストールのためにmultilibリポジトリを有効化する
  replace:
    path: /etc/pacman.conf
    regexp: '^#\[multilib\]\n#Include = /etc/pacman.d/mirrorlist'
    replace: |-
        [multilib]
        Include = /etc/pacman.d/mirrorlist
  become: yes

- name: 公式のパッケージをインストールする
  package:
    name:
      # 入力メソッド
      - fcitx5  
      - fcitx5-configtool
      - fcitx5-mozc
      # シェル・CLIツール
      - fish  
      - fisher
      - neofetch  # ターミナルのシステム情報表示
      - starship  # ターミナルプロンプト設定
      - less
      - fzf
      - neovim
      - unzip
      - wl-clipboard
      - nerdctl  # dockerコマンド代替
      - tree  # ディレクトリ表示ツール
      - uv  # pythonパッケージ管理
      # windowsエミュレーション
      - wine  
      - winetricks
      - wine-gecko
      - wine-mono
      - kdialog
    state: present
  become: yes

- name: AURのパッケージをインストールする
  kewlfft.aur.aur:
    use: yay
    name:
      - ttf-hackgen  # プログラミングフォント 白源 (はくげん／HackGen)
      - ghq  # リポジトリ管理
      - visual-studio-code-bin  #VSCode
      - asdf-vm
      - rancher-desktop
      - xkeysnail  # キーバインド変更
      - networkd-notify-git  # ネットワークについての通知
  become: yes
  become_user: aur_builder

- name: ディレクトリを作成する
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/Code/User
    - ~/.config/nvim
    - ~/.config/git
    - ~/.local/share/nvim/site/autoload
    - ~/.config/neofetch
    - ~/.config/fish
    - ~/.config/fisher

- name: ユーザーレベルの設定ファイルのリンクを作成する
  file:
    src: "{{ ansible_env.PWD }}/roles/{{ ansible_role_name }}/files/{{ item }}"
    dest: ~/{{ item }}
    state: link
  with_items:
    - .config/Code/User/keybindings.json
    - .config/Code/User/settings.json
    - .config/git/ignore
    - .config/nvim/init.vim
    - .config/chrome-flags.conf
    - .config/code-flags.conf
    - .config/neofetch/config.conf
    - .config/fish/config.fish
    - .config/fish/fzf_key_bindings.fish
    - .config/starship.toml

- name: テンプレートから設定ファイルを作成して配置する
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: gitconfig.j2, dest: ~/.config/git/config }

- name: Vim-Plugのスクリプトをダウンロードする
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Vim-Plugのプラグインをインストールする
  shell: nvim --headless +PlugInstall +qall
  args:
    creates: ~/.config/nvim/plugged
    executable: /bin/bash

- name: fisherでfishのプラグインをインストールする
  shell: fish -lc "fisher install {{ item }}"
  args:
    creates: ~/.config/fisher/github.com/{{ item }}
  with_items:
    - decors/fish-ghq
    - jethrokuan/fzf

- include_tasks: file_server.yml
- include_tasks: bluetooth.yml
- include_tasks: multimedia.yml
