- name: 公式のパッケージをインストールする
  package:
    name:
      # 画像
      - gimp
      - gimp-plugin-gmic
      - darktable
      - eog
      # 音楽
      - strawberry
      - gst-plugins-bad
      - gst-plugin-spotify
    state: present
  become: yes

- name: AURのパッケージをインストールする
  kewlfft.aur.aur:
    use: yay
    name:
      - gimp-plugin-export-layers
  become: yes
  become_user: aur_builder

- name: Flatpakをインストールする
  flatpak:
    name: org.zrythm.Zrythm
    state: present

