- name: Install packages
  package:
    name:
      - xorg
      - xorg-xinit
      - xorg-xmodmap
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - lm_sensors
      - dmenu
      - alsa-utils
      - pulseaudio
      - pulseaudio-equalizer
      - pavucontrol-qt
      - bluez
      - bluez-utils
      - bluez-libs
      - pulseaudio-bluetooth
      - blueman
      - bluedevil
      - gnome
      - dconf-editor
      - xf86-input-libinput
      - xorg-xinput
      - libinput
      - rustup
      # TODO: packages of fcitx5-im group.
      - fcitx5
      - fcitx5-configtool
      - fcitx5-qt
      - fcitx5-gtk
      - fcitx5-nord
      # スクリーンショット
      # https://wiki.archlinux.jp/index.php/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%AD%E3%83%A3%E3%83%97%E3%83%81%E3%83%A3
      - maim
      - xdotool
      - xclip
      # hyprland
      - hyprland 
      - hyprpaper
      - kitty
      - wofi
      - dolphin
      - dolphin-plugins
      - qt5ct
      - kvantum
      # ファイルプレビュー
      - kdegraphics-thumbnailers  # 画像ファイル、PDF、Blender アプリケーションファイル。
      - libheif  # HEIF ファイル
      - qt5-imageformats  # .webp、.tiff、.tga、.jp2 ファイル
      - kdesdk-thumbnailers  # サムネイルシステムのプラグイン
      - ffmpegthumbs  # 動画ファイル (ffmpeg ベース)
      - taglib  # 音声ファイル
    state: present
  become: yes

- name: aur install
  kewlfft.aur.aur:
    use: yay
    name:
      - ttf-cica
      - fcitx5-mozc-ut
      - kvantum-theme-nordic-git
      - papirus-folders-nordic
      - nordic-theme
      - nordic-kde-git
      - eww-wayland
  become: yes
  become_user: aur_builder

- name: Make sure environment variables are defined
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
  become: yes

- name: Make sure directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/X11
    - ~/.config/environment.d
    - ~/.config/fcitx5/conf
    - ~/.config/gestures
    - ~/.config/kitty/themes
    - ~/.config/hypr
    - ~/.config/eww

- name: Ensure dotfiles (files) are symlinked
  file:
    src: "{{ ansible_env.PWD }}/roles/de/files/{{ item.filename }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { filename: X11/xinitrc, dest: ~/.config/X11/xinitrc }
    - { filename: misc/xprofile, dest: ~/.xprofile }
    - { filename: misc/Xmodmap, dest: ~/.Xmodmap }
    - { filename: misc/fcitx5.conf, dest: ~/.config/environment.d/fcitx5.conf }
    - { filename: misc/classicui.conf, dest: ~/.config/fcitx5/conf/classicui.conf }
    - { filename: misc/gestures.kdl, dest: ~/.config/gestures/gestures.kdl }
    - { filename: misc/gestures.service, dest: ~/.config/systemd/user/gestures.service }
    - { filename: misc/kitty.conf, dest: ~/.config/kitty/kitty.conf }
    - { filename: misc/nordic.conf, dest: ~/.config/kitty/themes/nordic.conf }
    - { filename: misc/hyprland.conf, dest: ~/.config/hypr/hyprland.conf }
    - { filename: misc/eww.yuck, dest: ~/.config/eww/eww.yuck }
    - { filename: misc/eww.scss, dest: ~/.config/eww/eww.scss }

- name: "ALSA configuration"
  lineinfile:
      path: /etc/modprobe.d/alsa_base.conf
      line: 'options snd_hda_intel model=alc256-asus-mic power_save=0 power_save_controller=N'
      create: yes
  become: yes

# Bluetoothのためユーザーをlpグループに追加。
# https://wiki.archlinux.jp/index.php/Bluetooth
- name: adding existing user '{{ USER_NAME }}' to group lp, input
  user:
    name: '{{ USER_NAME }}'
    groups:
      - lp
      - input
    append: yes
  become: yes

- name: Make sure the GDM service is running
  systemd:
    name: gdm.service
    state: started
    enabled: yes
  become: yes

- name: Make sure the NetworkManager service is running
  systemd:
    name: NetworkManager.service
    state: started
    enabled: yes
  become: yes

# Bluetooth - ArchWikiBluetooth - ArchWiki 起動後に自動で有効にする
# https://wiki.archlinux.jp/index.php/Bluetooth#.E8.B5.B7.E5.8B.95.E5.BE.8C.E3.81.AB.E8.87.AA.E5.8B.95.E3.81.A7.E6.9C.89.E5.8A.B9.E3.81.AB.E3.81.99.E3.82.8B
- name: Make sure bluetooth power-on after boot/resume
  lineinfile:
    path: /etc/bluetooth/main.conf
    state: present
    regexp: '^#AutoEnable=false'
    line: 'AutoEnable=true'
  become: yes

# pulseaudio設定
# PulseAudio - ArchWiki
# https://wiki.archlinux.jp/index.php/PulseAudio#.E3.82.A4.E3.83.B3.E3.82.B9.E3.83.88.E3.83.BC.E3.83.AB
- name: Ensure pulseaudio config files are symlinked
  file:
    src: "{{ ansible_env.PWD }}/roles/de/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { src: default.pa, dest: ~/.config/pulse/default.pa }

# 3本指ドラッグ
- name: Install "ferstar/gestures" Rust package
  shell: cargo install --git https://github.com/ferstar/gestures.git

- name: Make sure directories for "ferstar/gestures" exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/gestures

- name: Ensure dotfiles (files) for "ferstar/gestures" are symlinked
  file:
    src: "{{ ansible_env.PWD }}/roles/de/files/{{ item.filename }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { filename: misc/gestures.kdl, dest: ~/.config/gestures/gestures.kdl }
    - { filename: misc/gestures.service, dest: ~/.config/systemd/user/gestures.service }

- name: Make sure "ferstar/gestures" service is running
  systemd:
    name: gestures.service
    state: started
    scope: user
    enabled: yes
