#!/bin/bash

EWW=`which eww`
CFG="$HOME/.config/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 5
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open bar
}

## Launch or close widgets accordingly
run_eww