- name: Install packages
  package:
    name:
      - fzf
      - neofetch
      - tree
      - htop
      - usbutils
      - kbd
      - eog
      # vscode GlassIt Linux https://marketplace.visualstudio.com/items?itemName=nowsci.glassit-linux
      - wmctrl
      - python-pipenv
      - wireless_tools
      - networkmanager
      - xsel  # 2022/04/23 kivyのプログラミングで必要になった。
      - python-cookiecutter
      - blender
      - geary
      - aws-vault
    state: present
  become: yes

- name: aur install
  kewlfft.aur.aur:
    use: yay
    name:
      - google-chrome
      - visual-studio-code-bin
      - chrome-gnome-shell
      - slack-desktop
      - asdf-vm
      - opendrop
      - notion-app
      - ngrok
  become: yes
  become_user: aur_builder

# vscode setting
- name: Make sure vscode setting directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/Code/User

- name: Ensure setting files are symlinked
  file:
    src: "{{ ansible_env.PWD }}/roles/misc/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: vscode/settings.json, dest: ~/.config/Code/User/settings.json }
    - { src: vscode/keybindings.json, dest: ~/.config/Code/User/keybindings.json }

# genshin test
- name: Install packages (genshin test)
  package:
    name:
      - lutris
      - vulkan-intel
      - vulkan-tools
      - xdelta3
      - xterm
      # wine
      - wine-staging
      - giflib
      - lib32-giflib
      - libpng
      - lib32-libpng
      - libldap
      - lib32-libldap
      - gnutls
      - lib32-gnutls
      - mpg123
      - lib32-mpg123
      - openal
      - lib32-openal
      - v4l-utils
      - lib32-v4l-utils
      - libpulse
      - lib32-libpulse
      - libgpg-error
      - lib32-libgpg-error
      - alsa-plugins
      - lib32-alsa-plugins
      - alsa-lib
      - lib32-alsa-lib
      - libjpeg-turbo
      - lib32-libjpeg-turbo
      - sqlite
      - lib32-sqlite
      - libxcomposite
      - lib32-libxcomposite
      - libxinerama
      - lib32-libgcrypt
      - libgcrypt
      - lib32-libxinerama
      - ncurses
      - lib32-ncurses
      - opencl-icd-loader
      - lib32-opencl-icd-loader
      - libxslt
      - lib32-libxslt
      - libva
      - lib32-libva
      - gtk3
      - lib32-gtk3
      - gst-plugins-base-libs
      - lib32-gst-plugins-base-libs
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      # 自動ツール
      - xdotool
      # 日本語文字化け対策
      - winetricks
    state: present
  become: yes