- name: Install packages
  package:
    name:
      - fzf
      - neofetch
      - tree
      - code
    state: present
  become: yes

- name: aur install
  aur:
    use: makepkg
    name:
      - google-chrome
  become: yes
  become_user: aur_builder
